{% set python_min = "3.10" %}
{% set name = "xarray-safe-s1" %}
{% set version = "2025.3.24" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 411cd11a5797a9be5ca082fb9101c52fae3cfe3dfe7b3508c576275a5b5a1910

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=64.0
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }}
    - geopandas
    - numpy
    - xarray >=2024.10.0
    - rasterio
    - rioxarray
    - lxml
    - jmespath
    - fsspec
    - pandas
    - shapely
    - pyproj
    - dask-core
    - affine
    - aiohttp

test:
  imports:
    - safe_s1
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/xarray-safe-s1/
  summary: Sentinel-1 SAR ESA - Copernicus mission python - xarray reader
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/umr-lops/xarray-safe-s1/
  doc_url: https://xarray-safe-s1.readthedocs.io/en/latest/
extra:
  recipe-maintainers:
    - yreynaud
    - agrouaze
    - vincelhx
